apiVersion: apps/v1
kind: Deployment
metadata:
  name: dydat-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dydat-backend
  template:
    metadata:
      labels:
        app: dydat-backend
    spec:
      containers:
      - name: dydat-backend
        image: 012823504146.dkr.ecr.eu-central-1.amazonaws.com/dydat-backend-v2:IMAGE_TAG
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: port
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: dbname 