apiVersion: v1
kind: Service
metadata:
  name: dydat-frontend-service
spec:
  selector:
    app: dydat-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer 