"""Aggiunge sr_card_json a stato_nodi_utente

Revision ID: 716b95629203
Revises: d5767045e1bb
Create Date: 2026-04-05 01:39:46.959343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '716b95629203'
down_revision: Union[str, None] = 'd5767045e1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stato_nodi_utente', sa.Column('sr_card_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stato_nodi_utente', 'sr_card_json')
    # ### end Alembic commands ###
