"""initial schema - all 17 tables

Revision ID: d5767045e1bb
Revises: 
Create Date: 2026-02-17 05:06:20.102346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5767045e1bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_definizioni',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('condizione', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rarita', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodi',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('materia', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Text(), server_default='standard', nullable=False),
    sa.Column('tipo_nodo', sa.Text(), server_default='operativo', nullable=False),
    sa.Column('definizioni_formali', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('formule_proprieta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('errori_comuni', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('esempi_applicazione', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parole_chiave', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temi',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('materia', sa.Text(), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('ordine_visualizzazione', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utenti',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('profilo_sintetizzato', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('profilo_sintetizzato_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('preferenze_tutor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contesto_personale', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('materie_attive', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('obiettivo_giornaliero_min', sa.Integer(), server_default=sa.text('20'), nullable=False),
    sa.Column('impostazioni_promemoria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('achievement_utente',
    sa.Column('utente_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.Text(), nullable=False),
    sa.Column('sbloccato_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement_definizioni.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('utente_id', 'achievement_id')
    )
    op.create_table('esercizi',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('nodo_id', sa.Text(), nullable=False),
    sa.Column('testo', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=True),
    sa.Column('difficolta', sa.Integer(), nullable=True),
    sa.Column('soluzione', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nodi_coinvolti', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['nodo_id'], ['nodi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_esercizi_nodo_id', 'esercizi', ['nodo_id'], unique=False)
    op.create_table('nodi_temi',
    sa.Column('nodo_id', sa.Text(), nullable=False),
    sa.Column('tema_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['nodo_id'], ['nodi.id'], ),
    sa.ForeignKeyConstraint(['tema_id'], ['temi.id'], ),
    sa.PrimaryKeyConstraint('nodo_id', 'tema_id')
    )
    op.create_table('note_utente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utente_id', sa.UUID(), nullable=False),
    sa.Column('nodo_id', sa.Text(), nullable=True),
    sa.Column('tema_id', sa.Text(), nullable=True),
    sa.Column('contenuto', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nodo_id'], ['nodi.id'], ),
    sa.ForeignKeyConstraint(['tema_id'], ['temi.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('percorsi_utente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utente_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('materia', sa.Text(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('descrizione_obiettivo', sa.Text(), nullable=True),
    sa.Column('nodi_target', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('nodo_iniziale_override', sa.Text(), nullable=True),
    sa.Column('stato', sa.Text(), server_default='attivo', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nodo_iniziale_override'], ['nodi.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relazioni',
    sa.Column('nodo_da', sa.Text(), nullable=False),
    sa.Column('nodo_a', sa.Text(), nullable=False),
    sa.Column('dipendenza', sa.Text(), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['nodo_a'], ['nodi.id'], ),
    sa.ForeignKeyConstraint(['nodo_da'], ['nodi.id'], ),
    sa.PrimaryKeyConstraint('nodo_da', 'nodo_a')
    )
    op.create_table('sessioni',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('utente_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=True),
    sa.Column('durata_prevista_min', sa.Integer(), nullable=True),
    sa.Column('durata_effettiva_min', sa.Integer(), nullable=True),
    sa.Column('nodi_lavorati', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('attivita_svolte', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('riepilogo', sa.Text(), nullable=True),
    sa.Column('stato', sa.Text(), server_default='attiva', nullable=False),
    sa.Column('stato_orchestratore', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessioni_utente_stato', 'sessioni', ['utente_id', 'stato'], unique=False)
    op.create_table('statistiche_giornaliere',
    sa.Column('utente_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('minuti_studio', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('nodi_completati', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('esercizi_svolti', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('esercizi_corretti', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('obiettivo_raggiunto', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('utente_id', 'data')
    )
    op.create_table('stato_nodi_utente',
    sa.Column('utente_id', sa.UUID(), nullable=False),
    sa.Column('nodo_id', sa.Text(), nullable=False),
    sa.Column('livello', sa.Text(), server_default='non_iniziato', nullable=False),
    sa.Column('presunto', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('spiegazione_data', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('esercizi_completati', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('errori_in_corso', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('contesto_sospensione', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sr_prossimo_ripasso', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sr_intervallo_giorni', sa.Float(), nullable=True),
    sa.Column('sr_facilita', sa.Float(), server_default=sa.text('2.5'), nullable=False),
    sa.Column('sr_ripetizioni', sa.Integer(), nullable=True),
    sa.Column('sr_stabilita', sa.Float(), nullable=True),
    sa.Column('sr_difficolta', sa.Float(), nullable=True),
    sa.Column('feynman_superato', sa.Boolean(), nullable=True),
    sa.Column('feynman_data', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('esercizi_consecutivi_ok', sa.Integer(), nullable=True),
    sa.Column('ripasso_post_feynman_ok', sa.Boolean(), nullable=True),
    sa.Column('ultima_interazione', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['nodo_id'], ['nodi.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('utente_id', 'nodo_id')
    )
    op.create_index('ix_stato_nodi_utente_livello', 'stato_nodi_utente', ['utente_id', 'livello'], unique=False)
    op.create_index('ix_stato_nodi_utente_sr', 'stato_nodi_utente', ['utente_id', 'sr_prossimo_ripasso'], unique=False)
    op.create_table('stato_temi_utente',
    sa.Column('utente_id', sa.UUID(), nullable=False),
    sa.Column('tema_id', sa.Text(), nullable=False),
    sa.Column('stato', sa.Text(), nullable=True),
    sa.Column('riepilogo_ai', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tema_id'], ['temi.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('utente_id', 'tema_id')
    )
    op.create_table('storico_errori',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utente_id', sa.UUID(), nullable=False),
    sa.Column('nodo_id', sa.Text(), nullable=False),
    sa.Column('tipo_errore', sa.Text(), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('contesto', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sessione_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nodo_id'], ['nodi.id'], ),
    sa.ForeignKeyConstraint(['sessione_id'], ['sessioni.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storico_esercizi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utente_id', sa.UUID(), nullable=False),
    sa.Column('nodo_focale_id', sa.Text(), nullable=False),
    sa.Column('esercizio_id', sa.Text(), nullable=True),
    sa.Column('esito', sa.Text(), nullable=False),
    sa.Column('nodo_causa_id', sa.Text(), nullable=True),
    sa.Column('nodi_coinvolti', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('tipo_errore', sa.Text(), nullable=True),
    sa.Column('tempo_risposta_sec', sa.Integer(), nullable=True),
    sa.Column('sessione_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['esercizio_id'], ['esercizi.id'], ),
    sa.ForeignKeyConstraint(['nodo_causa_id'], ['nodi.id'], ),
    sa.ForeignKeyConstraint(['nodo_focale_id'], ['nodi.id'], ),
    sa.ForeignKeyConstraint(['sessione_id'], ['sessioni.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_storico_esercizi_utente_nodo', 'storico_esercizi', ['utente_id', 'nodo_focale_id'], unique=False)
    op.create_table('turni_conversazione',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sessione_id', sa.UUID(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('ruolo', sa.Text(), nullable=False),
    sa.Column('contenuto', sa.Text(), nullable=True),
    sa.Column('azioni', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('segnali', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nodo_focale_id', sa.Text(), nullable=True),
    sa.Column('modello', sa.Text(), nullable=True),
    sa.Column('token_input', sa.Integer(), nullable=True),
    sa.Column('token_output', sa.Integer(), nullable=True),
    sa.Column('costo_stimato', sa.Float(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nodo_focale_id'], ['nodi.id'], ),
    sa.ForeignKeyConstraint(['sessione_id'], ['sessioni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_turni_conversazione_sessione_ordine', 'turni_conversazione', ['sessione_id', 'ordine'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_turni_conversazione_sessione_ordine', table_name='turni_conversazione')
    op.drop_table('turni_conversazione')
    op.drop_index('ix_storico_esercizi_utente_nodo', table_name='storico_esercizi')
    op.drop_table('storico_esercizi')
    op.drop_table('storico_errori')
    op.drop_table('stato_temi_utente')
    op.drop_index('ix_stato_nodi_utente_sr', table_name='stato_nodi_utente')
    op.drop_index('ix_stato_nodi_utente_livello', table_name='stato_nodi_utente')
    op.drop_table('stato_nodi_utente')
    op.drop_table('statistiche_giornaliere')
    op.drop_index('ix_sessioni_utente_stato', table_name='sessioni')
    op.drop_table('sessioni')
    op.drop_table('relazioni')
    op.drop_table('percorsi_utente')
    op.drop_table('note_utente')
    op.drop_table('nodi_temi')
    op.drop_index('ix_esercizi_nodo_id', table_name='esercizi')
    op.drop_table('esercizi')
    op.drop_table('achievement_utente')
    op.drop_table('utenti')
    op.drop_table('temi')
    op.drop_table('nodi')
    op.drop_table('achievement_definizioni')
    # ### end Alembic commands ###
