name: Debug Workflow Resolution

on:
  push:
    branches:
      - main

jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check Node version
        run: node --version 