name: Continuous Deployment

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY_BACKEND: dydat-backend
  ECR_REPOSITORY_FRONTEND: dydat-frontend

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_REGISTRY="${ACCOUNT_ID}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com"
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin "$ECR_REGISTRY"
          echo "registry=$ECR_REGISTRY" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/backend/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_BACKEND }}:latest
          cache-from: type=inline
          cache-to: type=inline,mode=max

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/frontend/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_FRONTEND }}:latest
          cache-from: type=inline
          cache-to: type=inline,mode=max

  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Update kube config
        run: aws eks update-kubeconfig --name dydat-main-cluster --region ${{ env.AWS_REGION }}

      - name: Create/Update DB Credentials Secret
        run: |
          # Get the ARN of the secret from Terraform output
          DB_SECRET_ARN=$(cd infra && terraform output -raw db_cluster_secret_arn)
          echo "Fetching secret from ARN: $DB_SECRET_ARN"

          # Get the secret value from AWS Secrets Manager
          SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id $DB_SECRET_ARN --query SecretString --output text)
          
          # Extract values from the JSON
          DB_HOST=$(echo $SECRET_JSON | jq -r .host)
          DB_PORT=$(echo $SECRET_JSON | jq -r .port)
          DB_USERNAME=$(echo $SECRET_JSON | jq -r .username)
          DB_PASSWORD=$(echo $SECRET_JSON | jq -r .password)
          DB_NAME=$(echo $SECRET_JSON | jq -r .dbname)

          # Create or update the Kubernetes secret
          kubectl create secret generic dydat-db-credentials \
            --from-literal=DB_HOST=$DB_HOST \
            --from-literal=DB_PORT=$DB_PORT \
            --from-literal=DB_USERNAME=$DB_USERNAME \
            --from-literal=DB_PASSWORD=$DB_PASSWORD \
            --from-literal=DB_NAME=$DB_NAME \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Restart deployments
        run: |
          kubectl rollout restart deployment backend-deployment 